### ISSUE TITLE
Typos on slide7.png

### ISSUE THREAD

**Issue by akien-mga** [SimonLarsen/90-Second-Portraits#2]
Hi,

There are a couple typos on slide7.png, but since it's a picture I can't easy fix them without the image source, hopefully you still have it.

"recieve" → "receive"
"galleri" → "gallery"

The two sentences in slide7.png also lack a dot at the end.

Thanks for this game, I love the concept and art :-)

**Comment by SimonLarsen** [comment]
Fixed in source now. Will update binaries later.

Also, thank you. :)
