### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by akien-mga** [SimonLarsen/90-Second-Portraits#3]
Basically copy pasting the content from http://ludumdare.com/compo/ludum-dare-31/?action=preview&uid=1980 does the trick, though you'll probably want to fix the title levels.

Also note that only the keys 1 to 6 can be used to change the display size, and not 1-7 as written on the above page.

**Comment by SimonLarsen** [comment]
I've added a basic readme for now. Will get back to your other issues when I can.
Thanks for reporting. :)

**Comment by akien-mga** [comment]
Nice, thanks! I packaged it for Mageia 5, it's really funny (and challenging for such a lousy drawer as myself :-).
